#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ ! -f /var/www/html/.env ]; then
	cp .env.example .env
    php artisan key:generate
    php artisan jwt:secret
fi

composer install
chmod o+w /var/www/html/storage/ -R
php /var/www/html/artisan app:install

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
